### ISSUE TITLE
Grundlagen der Lagersicherheit

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#10]
Korrektur lesen und ergänzen, um eine möglichst professionelle Extraseite zu erstellen

**Comment by LeoniOnGithub** [comment]
Tobi schreibt:
Bei der ersten Aktion seit Langem ist mir aufgefallen, dass vielen (jüngeren) grundlegende Lagersicherheit nur begrenzt bekannt ist. Das soll dieser Teil beheben. Zusätzliche Punkte oder Umformulierungen sind erwünscht.
Erste Hilfe?

Dies soll keine Anleitung zur ersten Hilfe werden, sondern insbesondere Jüngeren eine einfache Liste an Handlungsschritten geben, die kein zusätzliches Wissen oder Fähigkeiten (z.B. Puls o. Lüftröhre prüfen) abverlangt. Hier wäre es gut, wenn Menschen mit Sani Erfahrung einen Kommentar zu abgeben.

![grafik](https://user-images.githubusercontent.com/93880125/140787007-9613d149-a518-42d6-aa93-4682a4e9b61e.png)

**Comment by peribaeri** [comment]
aktueller Stand
![grundlagen](https://user-images.githubusercontent.com/86397847/142256593-dfb28340-81e4-499d-b79e-0e4b6d3fbdee.jpg)
