### ISSUE TITLE
Mengenkalkulationen Essen

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#12]
Hat jemand viel Erfahrung mit dem Kochen auf Fahrten und Lagern und kann folgende Mengenkalkulationen kommentieren/ ergänzen?

`So viel solltet ihr zur Sättigung pro Mahlzeit einkalkulieren (auf Fahrt eher mehr): ~50g Porridge/Person ~120g Trockenspätzle/Person ~120g trockene Nudeln/Person ~70g Reis/Person ~60g Couscous/Person ~3 mittelgroße (~170g) Kartoffeln/Person ~ ???(Gramm/ Scheiben/ Volumen/ Fläche????? kp was sinnvoll ist als Maßeinheit) Brot/Person`

**Comment by LeoniOnGithub** [comment]
Siehe Foto von Zettel aus dem Heim

Wie viel Brot? Unterschied Fahrt/ Lager??
Mengenangabe in gramm wurde sich gewünscht: https://strawpoll.de/6dzz935

**Comment by peribaeri** [comment]
gewicht von einem leeren Berghaferl ergänzen

**Comment by LeoniOnGithub** [comment]
"Bei Brötchen, Croissants oder Brezeln, die Sie zum Frühstück oder Brunch servieren wollen, sollten Sie 150 bis 200 Gramm pro Person anstreben.
Zu guter Letzt, wenn Sie Schwarzbrot oder Vollkornbrot als Teil der Zwischenmahlzeiten verwenden möchten, dann können Sie 200 Gramm davon pro Person verwenden. "
https://die-ganze-portion.de/wieviel-brot-pro-person/ 

Ernährungsexperten empfehlen, höchstens zwei Portionen Brot zu essen, und das täglich, das sind zwischen 250 und 450 Gramm. https://fitpeople.com/de/ernaehrung/wie-viel-brot-solltest-du-pro-tag-essen/

könnten uns daran orientieren:
![grafik](https://user-images.githubusercontent.com/93880125/144589827-9fdd0af9-6f16-4862-a677-ceffeb96c4af.png)
https://www.doppelherz.de/diaet-special/ernaehrung/mahlzeiten-und-portionsgroessen 


Was ziehen wir für ein Fazit?
