### ISSUE TITLE
Reihenfolge Lieder

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#13]
Wie sollen spezielle Lieder im LS geordnet sein?
Es geht dabei um die Einordnung von Sonderzeichen (mehr Wert als Buchstaben oder weniger?) und Anfänge, die optional/nicht wirlich Text (z.B. Eeeeeee von The lion sleeps tonight).

**Comment by LeoniOnGithub** [comment]
Welche Lieder fangen mit Sonderzeichen an?
Würde sagen wir orientieren uns am ersten richtigen Wort also bspw. "In the jungle" 
(glaube die Lieder sind ansonsten sehr richtig sortiert, das haben Tobi und ich im Sommer mal überprüft und einiges verschoben)

**Comment by peribaeri** [comment]
> Welche Lieder fangen mit Sonderzeichen an?

Weiß ich auch nicht genau, habe das aus dem alten github übernommen. Müsste man nochmal schauen, wenn man den ganzen Liederschuh nochmal auf korrekte Sortierung überprüft (eher kurz vor Probedruck-Deadline)

**Comment by LeoniOnGithub** [comment]
stimmt so weit (glaub ich)
sortiert wird nach den ersten Wörten, nicht nach Buchstaben, sodass bspw solch eine Reihenfolge richtig ist:
Sie saßen
Siebzehn Tage
Siehst du
