### ISSUE TITLE
Anfängerfreundliche Lieder

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#14]
Sammlung von Liedern, die leicht für Gitarrenanfänger sind

Dämmert von fern
Abends treten Elche
Roter Mond
Hier wächst kein Ahorn
Birkenring
Am Ural
Country Roads
Walk with the wind
Leaving on a jetplane
Anne Kaffekanne
Hallihallo
Piratenhafen

schwierig werden Lieder, sobald es Akkorde mit 
- Barré
- F-Dur
- h-Moll
- B-Dur
gibt.

Bitte weitere Lieder in den Kommentaren ergänzen (oder kommentieren, dass Lieder in der Liste nicht so nice zum Spielen sind für Anfänger)!

**Comment by Justus-VCP** [comment]
* Wind in den Augen
* Über meiner Heimat Frühling
* Es war an einem Sommertag
* Triodimali
