### ISSUE TITLE
Akkordtabelle am Ende

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#17]
- [x] - Sind alle im LS vorkommenden Akkorde drin?

- [x] - Sind alle abgedruckten Akkorde in der Tabelle korrekt (vom Spielen und vom Namen her)?

**Comment by LeoniOnGithub** [comment]
![grafik](https://user-images.githubusercontent.com/93880125/144515559-1678c30e-4e1c-44bc-8843-97aa8c1f0936.png)
Kommentare?
