### ISSUE TITLE
Grundlagen Gitarre spielen

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#18]
grundlegende Tipps und Weisheiten, die man als Gitarrenanfänger kennen sollte und möchte. Gewünscht: Sammlung an Tipps

Inspiration:
- Haltung der Hand
- was tun, wenn Akkorde "scheppern"?
- Barré lernen
- How to sich-selbst-motivieren-und-in-den-arsch-treten-um-gitarre-zu-lernen

**Comment by Justus-VCP** [comment]
* schummelgriffe für zb. F-Dur oder ähnliche Akkorde - ist vorallem für die Anfänger ganz hilfreich, da Barre nicht unbedingt super schnell zu lernen ist. So kann man aber schon früher anfangen in den Runden mitzuspielen, was die Motivation puscht
![06_DUR_Akkord_F-Dur_offen](https://user-images.githubusercontent.com/95183382/143780356-ca8cc83c-aa1e-40b5-8dd5-b9942763af35.png)
