### ISSUE TITLE
In dem dunklen Wald von Paganowo

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#2]
eigentlich ein russisches Lied, auf das ein inhaltlich anderer deutscher Text gedichtet wurde
Meldet euch bitte, wenn ihr den Inhalt der russischen Vorlage oder den deutschen Autor kennt

**Comment by Justus-VCP** [comment]
>Text: aus der Jugendbewegung
Melodie: Matwei Isaakowitsch Blanter (1903-1990), 1938
Der russische Originaltitel lautet "Katjuscka"<
Quelle: Der Gaul, Liederbuch des  BdP Niedersachsen
