### ISSUE TITLE
Fahrtenapotheke

### ISSUE THREAD

**Issue by LeoniOnGithub** [peribaeri/Liederschuh-ToDos#20]
https://www.malteser.de/aware/hilfreich/erste-hilfe-kasten-inhalt-und-verwendung-der-komponenten.html
Ablaufdatum beachten!

Tobi schreibt: 
Was gehört eurer meinung nach in eine Fahrtenapotheke/ Erste Hilfe Pack?
-     Pflaster
-     Stoffschere
-     Handschuhe
-     Wunddesinfektion
-     Zeckenkarte/ -zange
-     Wundverband
-     Kompresse
-     Dreieckstuch
-     Wärmedecke

**Comment by Justus-VCP** [comment]
* Feuchttücher:
Zwei Stück. Die Feuchttücher dienen zur Reinigung unverletzter Hautflächen. 
* Blasenpflaster! 
* Betaisodona Lösung? = Wunddesinfektion, aber nicht auf Alkoholbasis, hilft auch gegen Antibiotika-Resistente Bakterien

**Comment by LeoniOnGithub** [comment]
![grafik](https://user-images.githubusercontent.com/93880125/143867566-ddcdcc69-fe77-4eec-a7df-4bb0214f51e5.png)
So gut?

**Comment by Justus-VCP** [comment]
Ich hätte die Blasenpflaster vielleicht als eigenen Punkt angeführt und nicht als AddOn bei dem Pflasterset, Aber das ist nicht so unbedingt wichtig... Ansonsten sehr nice
