### ISSUE TITLE
Finale Liederauswahl

### ISSUE THREAD

**Issue by LeoniOnGithub** [peribaeri/Liederschuh-ToDos#28]
- Welche kommen raus? 
- Welche fehlen evtl noch?
- Wie viele Extraseiten entstehen dadurch?

Entscheidungstool finden, um viele Leute daran teilhaben zu lassen/ Diskussionen im Thing oder mit Interessierten

**Comment by LeoniOnGithub** [comment]
Ajde Jano, 
Greensleeves?, 
Ghost riders in the sky?, 
Scarborough fair 
loch lomond?, 
die gedanken sind frei, (lame, andere lieder mit gleicher aussage besser)
König der Kinder, Frühling 
(endlich trocknet), 
hallihallo, 
badibam?, 
john kanaka, 
manchmal des nachts (säuferlied?), 
irischer segen? (titel), 
mein kleines boot, 
deadd and gone?, 
nane tsora,
bürgerlied
kaspar
blinde katharina
trommellied der geusen?, 
humor, 
eala frya fresena, 
santy anno (wird gesungen aber doppelt mit santiano? -.-)
rumänienlied?
ich find die kohte nicht mehr

abschied im herbstwind
wir wollen zu lande ausfahren
(gleiche melodie wie uran im urin?)

**Comment by peribaeri** [comment]
- [x] Termin festlegen für Entscheidung oder geeignetes Abstimmungstool finden (Google Forms? --> alle Lieder die zur Rausschmeiß-Diskussion stehen dort eintragen, Maximalzahl an Drin-Bleibern festlegen (analog zur Menge, die rausgeschmissen werden muss))

**Comment by LeoniOnGithub** [comment]
>     *  Maximalzahl an Drin-Bleibern festlegen (analog zur Menge, die rausgeschmissen werden muss))

Brauchen nicht unbedingt ne Maximalzahl oder? Bin eigtl ganz froh wenn das Ding wieder bisschen dünner wird

**Comment by LeoniOnGithub** [comment]
Fernweh und Sonnenstrahl rein

Whiskey in the jar ist übrigens von The Dubliners zumindest haben die das ziemlich früh vertont (danach gab's ja noch Cover und so)

**Comment by LeoniOnGithub** [comment]
@peribaeri  du hattest dir noch Fernweh und Sonnenstrahl gewünscht, richtig?

**Comment by peribaeri** [comment]
> @peribaeri  du hattest dir noch Fernweh und Sonnenstrahl gewünscht, richtig?

ja richtig. Beide Lieder sind im Discord als pdf.

**Comment by peribaeri** [comment]
T-Rex vom Stamm Adler aus dem DPV (Per hat Text und Akkorde

**Comment by peribaeri** [comment]
UPDATE:

Fernweh, Sonnenstrahl, T-Rex aufgenommen

Whiskey in the jar ist urspr. ein irisches Volkslied aus dem 17. oder 18. jhd mit unbekanntem Autor, das mehrfach vertont wurde, u.a. von den dubliners, bryan adams und santiano. Infos von Wikipedia, Anmerkung wurde entsprechend angepasst.

**Comment by peribaeri** [comment]
**Abstimmung über evtl. rauszuschmeißende Lieder:**
läuft bis einschl. **28.11.** über folgenden Link:
https://forms.gle/9akM2x7zTDNoBEuS7

**Comment by LeoniOnGithub** [comment]
Meutenlieder neu?:

https://www.youtube.com/watch?v=37UAvOre720 das hier ist auch mega süß, hat der Flo empfohlen
Seeräuberopa Fabian wäre noch aus Pippi Langstrumpf
Paule Puhmanns Paddelboot
Wer sagt dass Mädchen dümmer sind
https://www.youtube.com/watch?v=UK2bFumR71M kann sowas cool sein? oder wird das nur scheiße?
https://www.youtube.com/watch?v=8ihVsrAJLug ?
