### ISSUE TITLE
Der Pfahl (Hommage-Strophe an Klotzi)

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#29]
Bitte kommentiert die letzte Sonderstrophe vom Pfahl, wo es um die Hommage an Klotzi geht. Metrisch, rythmisch und ggf. auch textlich ist das noch nicht das i-Tüpfelchen, daher sind wir auf kreative Ideen von euch angewiesen, wie diese Strophe noch schöner werden kann.
![Screenshot_20211108-183905_Chrome](https://user-images.githubusercontent.com/86397847/140791117-4fe09d6e-223c-42a3-95ea-578282ab4a99.jpg)

**Comment by LeoniOnGithub** [comment]
evtl nochmal Leute fragen, die dabei waren- Jens oder Fred (?) 
haben  das ja nur spontan erfunden und ist sicherlich nicht rhythmisch perfekt
