### ISSUE TITLE
Makedonsko

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#3]
Version mit korrekter Rechtschreibung wird gesucht. Wenn ihr eine habt, bitte melden.
Wenn ihr interessante Facts zu dem Lied habt, gerne auch.

- [ ] Entscheiden, ob das überhaupt rein soll. Wenns keiner kennt, brauchen wirs auch nicht im Liederschuh

**Comment by LeoniOnGithub** [comment]
Hatte ich schon verbessert, gibt aber unterschiedliche versionen- wird schon ungefähr stimmen
