### ISSUE TITLE
Abspannen

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#30]
- [ ] Skizze von katze aus dem neuesten Probedruck übertragen
- [ ] wo muss ich meinen Hering reinschlagen damit mir nachts nicht die Jurte auf den Kopf fällt und wie muss ich den fürs abspannen reinschlagen?

**Comment by LeoniOnGithub** [comment]
Ich fürchte die Skizze von Katze zeigt nur den alte Art den Abspannknoten zu machen, nicht die praktischste.

Bitte um eine Vorlage mit Bildern!

**Comment by LeoniOnGithub** [comment]
Kai hat mir schlaue Sachen geschrieben
