### ISSUE TITLE
Akkordkorrekturen

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#31]
hier bitte alles, was ihr noch geändert haben wollt an Akkorden (Ergänzung von Akkorden etc.) als Kommentar posten, dann können wir das übernehmen.

**Comment by peribaeri** [comment]
Schluchten des Balkans:
1 und 3 Zeile nach dem D ein `(D4 D)` einfügen

**Comment by LeoniOnGithub** [comment]
joooo ich hab schon das issue akkorde checke gemacht
