### ISSUE TITLE
Korbpolka (Extraseite)

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#35]
Melodie als Noten einfügen (damit z.B. Melodika, Akkordeon etc. auch die Melodie spielen können)

**Comment by peribaeri** [comment]
wir suchen jemanden, der uns die Melodie in Form eines 5-Linien-Systems (am besten einzeilig) aufschreiben kann

**Comment by Justus-VCP** [comment]
Wenn ich Zugriff zu dem vorläufigen Liederbuch bekomme kann ich mich da bei einigen Liedern gerne dran versuchen bzw. gibt es in meinem Verband schon einiges mit Melodie dabei.
Per hat meine Nummer von Sasi Dunkel bekommen, ansonsten unter justus.wenzel@gmx.de

**Comment by Justus-VCP** [comment]
Wenn ich die Melodie kennen bzw bekommen würde, könnte ich mich vllt daran versuchen
(Kann aber nichts vesprechen)
