### ISSUE TITLE
Politische Korrektheit bei Liedern

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#38]
welche Lieder sind problematisch und müssen noch korrigiert werden? Bei welchen Liedern ist das Ersatzwort noch nicht so super?
wo fehlen noch Anmerkungen?

**Comment by peribaeri** [comment]
Ore Ore
Johnnys Spelunke
Europas Zonen

**Comment by LeoniOnGithub** [comment]
In den Anmerkungen steht jetzt: "Hier wurde das Z-Wort ersetzt." und bei Europas Zonen auch die Erklärung warum das so ist.

**Comment by LeoniOnGithub** [comment]
Zu Panama könnte Paddy noch einen Kommentar schreiben zum Hintergrund.

**Comment by Justus-VCP** [comment]
Beim Bund der Boreas steht in deren Liederbuch zu jedem Lied in dem das Z-Wort vorkommt:
>Die Bezeichnung "Zigeuner" ist im deutschen Sprachraum die veraltete Bezeichnung der Sinti und Roma, welche diese Bezeichnung ablehnen. Grund dafür ist eine lange Verfolgungsgeschichte, die während des Nationalsozialismus gipfelte. Schätzungen zur Folge wurden etwa 500.000 Sinti und Roma während des Holocausts ermordet.<
Das ist deren Aussage um sich von dem Z-Wort zu distanzieren. Meiner Meinung nach fehlt da aber dann noch ein Satz, welcher das auch klar macht.
