### ISSUE TITLE
Meine Biber haben Fieber

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#40]
aktuell sind da irgendwie zwei verschiedene Versionen drin. Bin dafür, dass wir uns da für eine entscheiden.
Fände die Version mit `Meine Biber haben Fieber` am Anfang gut (so dass jede Strophe mit `Meine ...`
Bei der Version könnte man dann auch ganz viele Strophen zusammentragen, sodass die Doppelseite gut gefüllt ist. Beispiele für Strophen:
https://tabs.ultimate-guitar.com/tab/misc-traditional/meine-biber-haben-fieber-chords-2769982

**Comment by LeoniOnGithub** [comment]
Auf einer Seite ist eigtl gut, dann sparen wir eine Extraseite. Würde von den Strophen die coolsten raussuchen und als Fun Fact in die Anmerkung schreiben, dass es eigentlich ein richtiges Lied gibt

**Comment by peribaeri** [comment]
wurde sich für die Meine Biber Version entschieden. Es ist ein bisschen Platz geblieben um eigene Strophen hinzukritzeln
