### ISSUE TITLE
Inhaltsverzeichnis Pfahl,der

### ISSUE THREAD

**Issue by LeoniOnGithub** [peribaeri/Liederschuh-ToDos#41]
> **Zweite Frage:** Falls Votum für Nein: Wo sollen Lieder wie `Der Pfahl` einsortiert werden im IH? Option 1: Unter D (**D**er Pfahl) Option 2: Unter P (**P**fahl, der bzw. Der **P**fahl)
> 
>     * Lieder 2 Mal im IH aufführen (falls Nein: Lieder unter Artikel einsortieren (`Der Pfahl` unter `D`) (👍)
> 
>     * Lieder 2 Mal im IH aufführen (falls Nein: Lieder unter Nomen einsortieren (`Der Pfahl` unter `P`) (👎)

wie auf Indesign lösen? (inhaltsverzeichnis automatisch generieren)

_Originally posted by @LeoniOnGithub in https://github.com/peribaeri/Liederschuh-ToDos/issues/36#issuecomment-982045843_

**Comment by peribaeri** [comment]
erledigt, Alternativtitel (artikel und rest umgedreht) sind jetzt auch eingefügt
