### ISSUE TITLE
Vor Druck drüber schauen

### ISSUE THREAD

**Issue by LeoniOnGithub** [peribaeri/Liederschuh-ToDos#44]
- [x] Extraseiten sinnvoll platzieren, alles richtig mit doppelseitigen Liedern?
- [x] Extraseiten richtige Ebene

- [x] keine rosa Kästen sichtbar
- [x] Inhaltsverzeichnis aktualisieren (alles schwarz, Lieder eingerückt, Abstände angemessen)
- [x] Querverweise zwischen Liedern (Santiano, Nachtgeister, Star of the Cunty Down, Rucksack richtig einstellen)
- [x] WapBap Platz Dislike Charts

**Comment by peribaeri** [comment]
- [x] Seitenzahlen Anfängerfreundliche Lieder ergänzen (bei Hinweise für Gitarrenspieler)

**Comment by Justus-VCP** [comment]
Würde da auch gerne mithelfen, kann ich aber leider nicht ohne Vordruck oder zugriff auf eine Datei.
@Per kannst dich gerne mal privat bei mir melden, Saskia hatte dir glaube ich mal meine Nummer geschickt.

**Comment by LeoniOnGithub** [comment]
Finaler Druck:
- [x] Stammesauflage auf Cover, Impressum, Dieses Liederbuch gehört weg
- [x] alle Akkordänderungen fertig?
