### ISSUE TITLE
Mental Health Extraseite Sammlung

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#45]
Nummer gegen Kummer (https://www.nummergegenkummer.de/), Kinder- und Jugendtelefon: 116 111 (kostenlos), EU-weit erreichbar, montags-samstags 14-20 Uhr

https://familienportal.de/familienportal/lebenslagen/krise-und-konflikt/hilfe-kinder-jugendliche-notlagen

Telefonseelsorge: 0800 / 111 0 111 (evang.) , 0800 / 111 0 222 (kath.) oder 116 123 (rund um die Uhr erreichbar, kostenlos, deutschlandweit), Website: telefonseelsorge.de

https://www.u25-deutschland.de/
https://www.suizidprophylaxe.de/hilfsangebote/hilfsangebote/

Sozialpsychatrischer Dienst MTK: 06192 201-1761, https://www.mtk.org/Psychiatrische-Angebote-1807.htm

und akute Probleme (z.B. akute Suizidgedanken): 112

**Comment by LeoniOnGithub** [comment]
https://www.ich-bin-alles.de/
https://www.corona-und-du.info/
