### ISSUE TITLE
Ako Umram

### ISSUE THREAD

**Issue by peribaeri** [peribaeri/Liederschuh-ToDos#9]
- [x] Entscheiden, ob das in den LS soll

wenn ja: Version mit korrekter Rechtschreibung gesucht

**Comment by LeoniOnGithub** [comment]
Muss rein! :)
Rechtschreibung hatte ich glaube ich danach: http://balkanarama.com/ako_umram.htm korrigiert (nochmal mit akuteller Version abgleichen!)


Done!
